# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for NegativeCutter — standalone executable
# Build: pyinstaller NegativeCutter.spec

import os
import sys
from pathlib import Path

# Ensure the plugin directory is on sys.path so filmcrop can be found
# PyInstaller executes the spec file via exec(), so __file__ is not available.
# Use sys.argv[0] which points to the spec file path during build.
plugin_dir = os.path.dirname(os.path.abspath(sys.argv[0]))
if plugin_dir not in sys.path:
    sys.path.insert(0, plugin_dir)

block_cipher = None

a = Analysis(
    ['detect_thumb.py'],
    pathex=[plugin_dir],
    binaries=[],
    datas=[],
    hiddenimports=[
        # filmcrop package
        'filmcrop',
        'filmcrop.detector',
        'filmcrop.export',
        'filmcrop.api',
        # PIL image plugins (lazy-loaded, must be explicit for PyInstaller)
        'PIL.TiffImagePlugin',
        'PIL.JpegImagePlugin',
        'PIL.PngImagePlugin',
        'PIL.BmpImagePlugin',
        'PIL.GifImagePlugin',
        'PIL.WebPImagePlugin',
        'PIL.PpmImagePlugin',
        'PIL.PcxImagePlugin',
        'PIL.MpoImagePlugin',
        'PIL.IcnsImagePlugin',
        'PIL.IcoImagePlugin',
        'PIL.FliImagePlugin',
        'PIL.FpxImagePlugin',
        'PIL.FtexImagePlugin',
        'PIL.GbrImagePlugin',
        'PIL.ImImagePlugin',
        'PIL.ImtImagePlugin',
        'PIL.IptcImagePlugin',
        'PIL.McIdasImagePlugin',
        'PIL.MicImagePlugin',
        'PIL.MpegImagePlugin',
        'PIL.PalmImagePlugin',
        'PIL.PdfImagePlugin',
        'PIL.PixarImagePlugin',
        'PIL.PsdImagePlugin',
        'PIL.SgiImagePlugin',
        'PIL.SpiderImagePlugin',
        'PIL.SunImagePlugin',
        'PIL.TgaImagePlugin',
        'PIL.WalImageFile',
        'PIL.XbmImagePlugin',
        'PIL.XpmImagePlugin',
        'PIL.XVThumbImagePlugin',
        'PIL.DdsImagePlugin',
        'PIL.EpsImagePlugin',
        'PIL.FitsImagePlugin',
        'PIL.Hdf5StubImagePlugin',
        'PIL.BufrStubImagePlugin',
        'PIL.GribStubImagePlugin',
        'PIL.WmfImagePlugin',
        'PIL.TiffTags',
        # numpy submodules commonly needed at runtime
        'numpy.core._dtype_ctypes',
        'numpy.core._multiarray_tests',
        'numpy.core._multiarray_umath',
        'numpy.core._operand_flag_tests',
        'numpy.core._rational_tests',
        'numpy.core._struct_ufunc_tests',
        'numpy.core._umath_tests',
        'numpy.core.arrayprint',
        'numpy.core.defchararray',
        'numpy.core.einsumfunc',
        'numpy.core.fromnumeric',
        'numpy.core.function_base',
        'numpy.core.getlimits',
        'numpy.core.memmap',
        'numpy.core.multiarray',
        'numpy.core.numeric',
        'numpy.core.numerictypes',
        'numpy.core.overrides',
        'numpy.core.records',
        'numpy.core.shape_base',
        'numpy.core.umath',
        'numpy.lib.format',
        'numpy.lib.mixins',
        'numpy.lib.npyio',
        'numpy.lib.polynomial',
        'numpy.lib.scimath',
        'numpy.lib.shape_base',
        'numpy.lib.stride_tricks',
        'numpy.lib.twodim_base',
        'numpy.lib.type_check',
        'numpy.lib.ufunclike',
        'numpy.lib.user_array',
        'numpy.lib.utils',
        'numpy.linalg.lapack_lite',
        'numpy.linalg._umath_linalg',
        'numpy.random._common',
        'numpy.random._bounded_integers',
        'numpy.random._generator',
        'numpy.random._mt19937',
        'numpy.random._pcg64',
        'numpy.random._philox',
        'numpy.random._sfc64',
        'numpy.random.bit_generator',
        'numpy.random.mtrand',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude heavy optional packages to keep binary small
        'tkinter',
        'matplotlib',
        'scipy',
        'pandas',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'IPython',
        'jupyter',
        'notebook',
        'pytest',
        'unittest',
        'pydoc',
        'doctest',
        'optparse',
        'calendar',
        'ftplib',
        'smtplib',
        'xmlrpc',
        'idlelib',
        # Exclude packages pulled in by PyInstaller hooks but not used by detect_thumb
        'setuptools',
        'pydantic',
        'pydantic_core',
        'packaging',
        'yaml',
        'charset_normalizer',
        'defusedxml',
        'typing_extensions',
        'typing_inspection',
        'annotated_types',
        'mypy',
        'mypy_extensions',
        'altgraph',
        'macholib',
        'playwright',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='NegativeCutter',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    onefile=False,
)
